# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_6/design_6.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6 || ORIG_REF_NAME==design_6} -quiet] -quiet

# IP: bd/design_6/ip/design_6_Pong_Top2_0_0/design_6_Pong_Top2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_Pong_Top2_0_0 || ORIG_REF_NAME==design_6_Pong_Top2_0_0} -quiet] -quiet

# IP: bd/design_6/ip/design_6_Sync_To_Count2_0_0/design_6_Sync_To_Count2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_Sync_To_Count2_0_0 || ORIG_REF_NAME==design_6_Sync_To_Count2_0_0} -quiet] -quiet

# IP: bd/design_6/ip/design_6_VGA_Sync_Porch_0_0/design_6_VGA_Sync_Porch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_VGA_Sync_Porch_0_0 || ORIG_REF_NAME==design_6_VGA_Sync_Porch_0_0} -quiet] -quiet

# IP: bd/design_6/ip/design_6_VGA_Sync_Pulses_0_0/design_6_VGA_Sync_Pulses_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_VGA_Sync_Pulses_0_0 || ORIG_REF_NAME==design_6_VGA_Sync_Pulses_0_0} -quiet] -quiet

# IP: bd/design_6/ip/design_6_util_vector_logic_0_0/design_6_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_util_vector_logic_0_0 || ORIG_REF_NAME==design_6_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_6/ip/design_6_Debounce_Switch_3_0/design_6_Debounce_Switch_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_Debounce_Switch_3_0 || ORIG_REF_NAME==design_6_Debounce_Switch_3_0} -quiet] -quiet

# IP: bd/design_6/ip/design_6_Debounce_Switch_4_0/design_6_Debounce_Switch_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_Debounce_Switch_4_0 || ORIG_REF_NAME==design_6_Debounce_Switch_4_0} -quiet] -quiet

# IP: bd/design_6/ip/design_6_Debounce_Switch_0_0/design_6_Debounce_Switch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_Debounce_Switch_0_0 || ORIG_REF_NAME==design_6_Debounce_Switch_0_0} -quiet] -quiet

# IP: bd/design_6/ip/design_6_Debounce_Switch_2_0/design_6_Debounce_Switch_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_Debounce_Switch_2_0 || ORIG_REF_NAME==design_6_Debounce_Switch_2_0} -quiet] -quiet

# IP: bd/design_6/ip/design_6_Debounce_Switch_1_0/design_6_Debounce_Switch_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_Debounce_Switch_1_0 || ORIG_REF_NAME==design_6_Debounce_Switch_1_0} -quiet] -quiet

# IP: bd/design_6/ip/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_6/ip/design_6_hdmi_tx_0_0/design_6_hdmi_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_6_hdmi_tx_0_0 || ORIG_REF_NAME==design_6_hdmi_tx_0_0} -quiet] -quiet

# XDC: /home/wfort/Xilinx_HardData/ip_repo/edit_myip_pong2_v1_0.gen/sources_1/bd/design_6/ip/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wfort/Xilinx_HardData/ip_repo/edit_myip_pong2_v1_0.gen/sources_1/bd/design_6/ip/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wfort/Xilinx_HardData/ip_repo/edit_myip_pong2_v1_0.gen/sources_1/bd/design_6/ip/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0_ooc.xdc

# XDC: /home/wfort/Xilinx_HardData/ip_repo/edit_myip_pong2_v1_0.gen/sources_1/bd/design_6/ip/design_6_clk_wiz_0_0/design_6_clk_wiz_0_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_6_clk_wiz_0_0 || ORIG_REF_NAME==design_6_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/wfort/Xilinx_HardData/ip_repo/edit_myip_pong2_v1_0.gen/sources_1/bd/design_6/design_6_ooc.xdc
