domain_path: C:\Users\harsh\Downloads\SoCFinalProject\Task3\Vitis_Task3\platform\export\platform\sw\standalone_microblaze_riscv_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
