#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XAXIDMA_NUM_INSTANCES 1

/* Definitions for peripheral AXI_DMA_0 */
#define XPAR_AXI_DMA_0_COMPATIBLE "xlnx,axi-dma-7.1"
#define XPAR_AXI_DMA_0_BASEADDR 0x41e00000
#define XPAR_AXI_DMA_0_HIGHADDR 0x41e0ffff
#define XPAR_AXI_DMA_0_SG_INCLUDE_STSCNTRL_STRM 0x0
#define XPAR_AXI_DMA_0_INCLUDE_MM2S 0x1
#define XPAR_AXI_DMA_0_INCLUDE_MM2S_DRE 0x1
#define XPAR_AXI_DMA_0_MM2S_DATA_WIDTH 0x20
#define XPAR_AXI_DMA_0_INCLUDE_S2MM 0x0
#define XPAR_AXI_DMA_0_INCLUDE_S2MM_DRE 0x0
#define XPAR_AXI_DMA_0_S2MM_DATA_WIDTH 0x20
#define XPAR_AXI_DMA_0_INCLUDE_SG 0x0
#define XPAR_AXI_DMA_0_NUM_MM2S_CHANNELS 0x1
#define XPAR_AXI_DMA_0_NUM_S2MM_CHANNELS 0x1
#define XPAR_AXI_DMA_0_MM2S_BURST_SIZE 0x10
#define XPAR_AXI_DMA_0_S2MM_BURST_SIZE 0x10
#define XPAR_AXI_DMA_0_MICRO_DMA 0x0
#define XPAR_AXI_DMA_0_ADDRWIDTH 0x20
#define XPAR_AXI_DMA_0_SG_LENGTH_WIDTH 0x10

/* Canonical definitions for peripheral AXI_DMA_0 */
#define XPAR_XAXIDMA_0_BASEADDR 0x41e00000
#define XPAR_XAXIDMA_0_HIGHADDR 0x41e0ffff
#define XPAR_XAXIDMA_0_ADDRWIDTH 0x20
#define XPAR_XAXIDMA_0_COMPATIBLE "xlnx,axi-dma-7.1"
#define XPAR_XAXIDMA_0_INCLUDE_MM2S 0x1
#define XPAR_XAXIDMA_0_INCLUDE_MM2S_DRE 0x1
#define XPAR_XAXIDMA_0_INCLUDE_S2MM 0x0
#define XPAR_XAXIDMA_0_INCLUDE_S2MM_DRE 0x0
#define XPAR_XAXIDMA_0_INCLUDE_SG 0x0
#define XPAR_XAXIDMA_0_MM2S_DATA_WIDTH 0x20
#define XPAR_XAXIDMA_0_MM2S_BURST_SIZE 0x10
#define XPAR_XAXIDMA_0_MICRO_DMA 0x0
#define XPAR_XAXIDMA_0_NUM_MM2S_CHANNELS 0x1
#define XPAR_XAXIDMA_0_NUM_S2MM_CHANNELS 0x1
#define XPAR_XAXIDMA_0_SG_INCLUDE_STSCNTRL_STRM 0x0
#define XPAR_XAXIDMA_0_S2MM_DATA_WIDTH 0x20
#define XPAR_XAXIDMA_0_S2MM_BURST_SIZE 0x10
#define XPAR_XAXIDMA_0_SG_LENGTH_WIDTH 0x10

#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral AXI_BRAM_CTRL_1 */
#define XPAR_AXI_BRAM_CTRL_1_COMPATIBLE "xlnx,axi-bram-ctrl-4.1"
#define XPAR_AXI_BRAM_CTRL_1_BASEADDR 0xc0000000
#define XPAR_AXI_BRAM_CTRL_1_HIGHADDR 0xc000ffff
#define XPAR_AXI_BRAM_CTRL_1_DATA_WIDTH 0x20
#define XPAR_AXI_BRAM_CTRL_1_ECC 0x0
#define XPAR_AXI_BRAM_CTRL_1_FAULT_INJECT 0x0
#define XPAR_AXI_BRAM_CTRL_1_CE_FAILING_REGISTERS 0x0
#define XPAR_AXI_BRAM_CTRL_1_BRAM_CORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_AXI_BRAM_CTRL_1_UE_FAILING_REGISTERS 0x0
#define XPAR_AXI_BRAM_CTRL_1_BRAM_UNCORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_AXI_BRAM_CTRL_1_BRAM_ECC_STATUS_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_BRAM_CTRL_1_BRAM_CORRECTABLE_COUNTER_BITS 0x0
#define XPAR_AXI_BRAM_CTRL_1_ECC_ONOFF_REGISTER 0x0
#define XPAR_AXI_BRAM_CTRL_1_ECC_ONOFF_RESET_VALUE 0x0
#define XPAR_AXI_BRAM_CTRL_1_WRITE_ACCESS 0x0
#define XPAR_AXI_BRAM_CTRL_1_BRAM_MEM_BASE_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_1_BRAM_MEM_HIGH_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_1_MEM_CTRL_BASE_ADDRESS 0x0
#define XPAR_AXI_BRAM_CTRL_1_MEM_CTRL_HIGH_ADDRESS 0x0

/* Canonical definitions for peripheral AXI_BRAM_CTRL_1 */
#define XPAR_XBRAM_0_BASEADDR 0xc0000000
#define XPAR_XBRAM_0_HIGHADDR 0xc000ffff
#define XPAR_XBRAM_0_BRAM_CORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_XBRAM_0_BRAM_UNCORRECTABLE_FAILING_DATA_REGS 0x0
#define XPAR_XBRAM_0_BRAM_ECC_STATUS_INTERRUPT_PRESENT 0x0
#define XPAR_XBRAM_0_BRAM_CORRECTABLE_COUNTER_BITS 0x0
#define XPAR_XBRAM_0_BRAM_MEM_BASE_ADDRESS 0x0
#define XPAR_XBRAM_0_BRAM_MEM_HIGH_ADDRESS 0x0
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,axi-bram-ctrl-4.1"
#define XPAR_XBRAM_0_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_DATA_WIDTH 0x20
#define XPAR_XBRAM_0_ECC 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_RESET_VALUE 0x0
#define XPAR_XBRAM_0_FAULT_INJECT 0x0
#define XPAR_XBRAM_0_MEM_CTRL_BASE_ADDRESS 0x0
#define XPAR_XBRAM_0_MEM_CTRL_HIGH_ADDRESS 0x0
#define XPAR_XBRAM_0_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_WRITE_ACCESS 0x0

#define XPAR_XGPIO_NUM_INSTANCES 1

/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_0_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x4000ffff
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_0_IS_DUAL 0x0
#define XPAR_AXI_GPIO_0_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_XGPIO_0_BASEADDR 0x40000000
#define XPAR_XGPIO_0_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x4
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_0_IS_DUAL 0x0

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x2580
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x2580
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/* Definitions for peripheral MYIP_PONG2_0 */
#define XPAR_MYIP_PONG2_0_BASEADDR 0x44a00000
#define XPAR_MYIP_PONG2_0_HIGHADDR 0x44a0ffff

/* Canonical definitions for peripheral MYIP_PONG2_0 */
#define XPAR_MYIP_PONG2_EDIT1_0_BASEADDR 0x44a00000
#define XPAR_MYIP_PONG2_EDIT1_0_HIGHADDR 0x44a0ffff

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x2000
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x21fff
#define XPAR_AXI_BRAM_0_BASEADDRESS 0xc0000000
#define XPAR_AXI_BRAM_0_HIGHADDRESS 0xc000ffff

/*  CPU parameters definition */
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0
#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_RISCV_D_LMB 1
#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7s50"

#endif  /* end of protection macro */